DROP DATABASE IF EXISTS user_db;

CREATE DATABASE user_db;

USE user_db;

CREATE TABLE users (
   id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   username VARCHAR(256) NOT NULL,
   password_hash VARCHAR(256) NOT NULL,
   userRole TINYINT DEFAULT 0 NOT NULL COMMENT '0 - User, 1 - Admin',
   createTime DATETIME DEFAULT CURRENT_TIMESTAMP,
   activeTime DATETIME DEFAULT CURRENT_TIMESTAMP,
   isDeleted TINYINT DEFAULT 0 NOT NULL COMMENT '0 - Not deleted, 1 - Deleted'
);